version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: utec
      POSTGRES_DB: ms_usuarios   # <- mejor sin guiones
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # <- OK, pero puedes quitarlo si no accedes desde fuera
    networks:
      - ms-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - ms-network

  ms-usuario:
    build: .
    container_name: usuario-service
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: root
      DB_PASSWORD: utec
      DB_NAME: ms_usuarios
    networks:
      - ms-network

volumes:
  postgres-data:

networks:
  ms-network:
